[package]
name = "felix-transport"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
quinn = "0.11"
tokio = { workspace = true, features = ["io-util"] }

[dev-dependencies]
rcgen = "0.12"
rustls = "0.23"
