[package]
name = "broker"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
felix-broker = { path = "../../crates/felix-broker" }
felix-transport = { path = "../../crates/felix-transport" }
felix-wire = { path = "../../crates/felix-wire" }
felix-storage = { path = "../../crates/felix-storage" }
bytes = { workspace = true }
quinn = "0.11"
rcgen = "0.12"
rustls = "0.23"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
