[package]
name = "broker"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
felix-broker = { path = "../../crates/felix-broker" }
felix-storage = { path = "../../crates/felix-storage" }
bytes = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
